### ISSUE TITLE
Add passenger button placed in order  improperly

### ISSUE THREAD

**Issue by tnovak-olin** [santosfamilyfoundation/RuinaMain#101]
The add new passenger button appears below the driver of a vehicle but appears above the passengers in the vehicle. This placement feels unnatural and disruptive to the flow of the app. Additional
 this placement is inconsistent with the add new vehicle section which appears after all of the vehicle sections.
![reorder add passenger](https://user-images.githubusercontent.com/42981223/115296207-48f56800-a120-11eb-958a-b8a75e4a6eec.png)

**Comment by tnovak-olin** [comment]
problem persists with occupants of vehicles (passengers when you remove a driver), as well as non motorists

**Comment by coverney** [comment]
This isn't an issue for tablets since multiple cards are in the same row
