### ISSUE TITLE
Initial contact point Popup not displaying text and has a small diagram

### ISSUE THREAD

**Issue by tnovak-olin** [santosfamilyfoundation/RuinaMain#108]
the more information popup from the inital contact point question does not display the intended text and the diagram in the popup is small and hard to read.

![Screenshot_20210430-213352_Ruina](https://user-images.githubusercontent.com/42981223/116768137-75539300-aa02-11eb-83dd-1d0a4817ea0b.jpg)

**Comment by coverney** [comment]
Next steps here would be making the info popups larger or by making the image larger. One thing that could be done is having the size of the tooltip windows be adjustable
