### ISSUE TITLE
Expand scanning a drivers license to fill out more questions

### ISSUE THREAD

**Issue by tnovak-olin** [santosfamilyfoundation/RuinaMain#110]
Scanning a Drivers license will not update the following questions even though it probably should:
First Name
Middle in ital
Sex
Drivers License Jurisdiction
Name of Jurisdiction
Commercial Drivers License

Additionally the City/Town question is correctly filled out but has not been confirmed (it does not have a green bar)

**Comment by coverney** [comment]
First name and middle initial are filled out, but the following fields aren't filled out
- Sex
- Drivers License Jurisdiction Type
- Name of Jurisdiction
- Commercial Drivers License

Something to do here is trying to parse more data from the barcode scanning and fill out more fields. Another thing to do is format the data so they aren't all capitalized
